MVC1/Models/ParticipantCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC1.Models
{
    public class ParticipantCreateViewModel
    {
        public ParticipantViewModel Participant { get; set; }

        public ParticipantListViewModel ParticipantList { get; set; }
    }
}

MVC1/Models/ParticipantListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC1.Models
{
    public class ParticipantListViewModel
    {
        public List<ParticipantViewModel> ParticipantList { get; set; }
    }
}

MVC1/Models/ParticipantViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC1.Models
{
    public class ParticipantViewModel
    {
        public int Id { get; set; }

        [DisplayName("Namn")]
        [Required]
        [RegularExpression(@"^[a-zA-ZåäöÅÄÖ ]{2,40}$", ErrorMessage ="Mellan 2 och 40 bokstäver krävs.")]
        public string Name { get; set; }

        [DisplayName("Födelsedag")]
        [Required]
        [Range(19000000, 20100000, ErrorMessage ="Felaktigt födelsadatum, ange på formeln ÅÅÅÅMMDD och se till att deltagaren måste var född före 2010")]
        public int Birthday { get; set; }

        [DisplayName("Klubb")]
        [Required]
        [MaxLength(50,ErrorMessage ="För långt klubbnamn")]
        public string Team { get; set; }
    }
}

MVC1/Controllers/MainController.cs
using MVC1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC1.Controllers
{
    public class MainController : Controller
    {
        static List<ParticipantViewModel> participantList = new List<ParticipantViewModel>();
        
        // GET: Main
        public ActionResult Index()
        {

            return View();
            //return View(participantList);
        }

        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }
    }
   
}

MVC1/Controllers/ParticipantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC1.Models;

namespace MVC1.Controllers
{
    public class ParticipantController : Controller
    {
        static List<ParticipantViewModel> participantList = new List<ParticipantViewModel>();

        public ActionResult Index()
        {
            return View(participantList);
        }

        [HttpGet]  
        public ActionResult Create()
        {
            ParticipantListViewModel participantListViewModel = new ParticipantListViewModel();

            participantListViewModel.ParticipantList = participantList;
            ParticipantCreateViewModel model = new ParticipantCreateViewModel
            {
                Participant = new ParticipantViewModel(),
                ParticipantList = participantListViewModel
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(ParticipantCreateViewModel _model)
        {

            if (participantList.Count > 0)
            {
                _model.Participant.Id = participantList.Max(x => x.Id) + 1;
            }
            else
            {
                _model.Participant.Id = 1;

            }

            participantList.Add(_model.Participant);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Modify(ParticipantViewModel _model)
        {

            return View(_model);
        }

        [HttpPost]
        public ActionResult Modify(ParticipantViewModel _model, string save, string delete)
        {
            var tmpProduct = participantList.Find(x => x.Id == _model.Id);
            if (save != null)
            {
                tmpProduct.Name = _model.Name;
                tmpProduct.Birthday = _model.Birthday;
                tmpProduct.Team = _model.Team;
            }
            else if (delete != null)
            {
                participantList.Remove(tmpProduct);
            }
            return RedirectToAction("Index");
        }

        public ActionResult NameList()
        {
            return View(participantList);
        }

        public PartialViewResult ParticipantList()
        {
            return PartialView("ParticipantListPartial", participantList);
        }


    }

}

MVC1/Views/Main/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}

<h2>Kontakt</h2>
<p>Skonsmons@halvmara.se</p>

MVC1/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}

<h2>Skönsmons Halvmaraton</h2>
<br/>

<p>Välkomna till årets upplaga av Skönsmons Halvmaraton!!</p>

@Html.ActionLink("Kontakta oss", "Contact", "Main", null)

MVC1/Views/Participant/Create.cshtml
@model MVC1.Models.ParticipantCreateViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class= "form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "")

        <div class="form-group">
            @Html.LabelFor(model => model.Participant.Name, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Participant.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Participant.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Participant.Birthday, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Participant.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Participant.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Participant.Team, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Participant.Team, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Participant.Team, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-offset-1 col-md-1">
            <input type="submit" value="Lägg till"/>
        </div>
    </div>

    <div class="row">
        @Html.Partial("ParticipantListPartial", Model.ParticipantList.ParticipantList)
    </div>

}

MVC1/Views/Participant/Index.cshtml
@model List<MVC1.Models.ParticipantViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
    var temp = new MVC1.Models.ParticipantViewModel();
}


    @Html.Partial("ParticipantListPartial", Model)

MVC1/Views/Participant/Modify.cshtml
@model MVC1.Models.ParticipantViewModel

@{
    ViewBag.Title = "Modify";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}



@using (Html.BeginForm())
{
    <hr />
    <div class="form-group">
        <div class="input-group col-md-5">
            <div class="input-group-addon">
                @Html.DisplayNameFor(x => x.Name)
            </div>
            @Html.EditorFor(x => x.Name, new { htmlAttributes = new { @value = Model.Name, @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        <div class="input-group col-md-5">
            <div class="input-group-addon">
                @Html.DisplayNameFor(x => x.Birthday)
            </div>
            @Html.EditorFor(x => x.Birthday, new{htmlAttributes = new { @value = Model.Birthday, @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <div class="input-group col-md-5">
            <div class="input-group-addon">
                @Html.DisplayNameFor(x => x.Team)
            </div>
            @Html.EditorFor(x => x.Team,new{htmlAttributes = new { @value = Model.Team ,@class = "form-control" } })
        </div>
    </div>
    <div>
        <input type="submit" value="Uppdatera" name="save" class="btn-success btn-xs" />
        <input type="submit" value="Ta bort deltagare" name="delete" class="btn-danger btn-group-lg" />
    </div>
}

MVC1/Views/Participant/NameList.cshtml
@model List<MVC1.Models.ParticipantViewModel>

@{
    ViewBag.Title = "NameList";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}

<h2>Namnlista</h2>

<div>
    @foreach (var product in Model)
    {
        <div>
            <dl class="KlickEvent">
                <dt>@Html.DisplayNameFor(x => product.Name)</dt>
                <dd>@Html.DisplayFor(x => product.Name)</dd>
            </dl>
            <dl class="AttToggla" style="display:none">
                <dt>@Html.DisplayNameFor(x => product.Birthday)</dt>
                <dd>@Html.DisplayFor(x => product.Birthday)</dd>

                <dt>@Html.DisplayNameFor(x => product.Team)</dt>
                <dd>@Html.DisplayFor(x => product.Team)</dd>
            </dl>
        </div>
    }
</div>
<script>
    $(document).ready(function () {
        $(".KlickEvent").click(function () {
            $(this).siblings(".AttToggla").slideToggle("fast");
        });

    });

</script>

MVC1/Views/Participant/Order.cshtml
@model List<MVC1.Models.ParticipantViewModel>

@{
    ViewBag.Title = "Order";
    Layout = "~/Views/Shared/LayoutPage.cshtml";
}

<h2>Order</h2>

<div>
    @foreach (var product in Model)
    {
        <div>
            <dl class="KlickEvent">
                <dt>@Html.DisplayNameFor(x => product.Name)</dt>
                <dd>@Html.DisplayFor(x => product.Name)</dd>
            </dl>
            <dl class="AttToggla" style="display:none">
                <dt>@Html.DisplayNameFor(x => product.Birthday)</dt>
                <dd>@Html.DisplayFor(x => product.Birthday)</dd>

                <dt>@Html.DisplayNameFor(x => product.Team)</dt>
                <dd>@Html.DisplayFor(x => product.Team)</dd>
            </dl>
        </div>
    }
</div>
<script src="~/Scripts/Custom/JQuery-Own.js"></script>

MVC1/Views/Participant/ParticipantListPartial.cshtml
@model List<MVC1.Models.ParticipantViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/PartialLayoutPage.cshtml";
    var temp = new MVC1.Models.ParticipantViewModel();
}


<div >
    <hr />
    <h3>Anmälda till tävlingen</h3>
    @if (Model.Count() == 0)
    {
        <h4>Ingen är anmäld till tävlingen än</h4>
    }
    else
    {
        <table class="table table-bordered table-striped table-hover">
            <tr>
                <th>@Html.DisplayNameFor(x => temp.Name)</th>
                <th>@Html.DisplayNameFor(x => temp.Birthday)</th>
                <th>@Html.DisplayNameFor(x => temp.Team)</th>
            </tr>
            @foreach (var participant in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => participant.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(x => participant.Birthday)
                    </td>
                    <td>
                        @Html.DisplayFor(x => participant.Team)
                    </td>
                    <td>
                        @Html.ActionLink("Ändra", "Modify", participant)
                    </td>
                </tr>
            }

        </table>
    }
    

</div>

MVC1/Views/Shared/LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script> 
</head>
<body>
    <div class="col-md-offset-1 row">
        @Html.ActionLink("Hem", "Index", "Main", null, new {@class ="btn btn-info"})
        @Html.ActionLink("Anmälda", "Index", "Participant", null, new { @class = "btn btn-primary" })
        @Html.ActionLink("Anmälan", "Create", "Participant", null,  new {@class = "btn btn-primary" })
        @Html.ActionLink("Namnlista", "NameList", "Participant", null,  new { @class = "btn btn-primary" })
    </div>
    <div class="row col-md-offset-1">
        @RenderBody()
    </div>

</body>
</html>

MVC1/Views/Shared/PartialLayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div>
        @RenderBody()
    </div>

</body>
</html>

MVC1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>